stages:
  - build

image: ruby:2.7


build_project:
  stage: build
  tags:
    - ios
  script:
    - rm -rf ~/realm.memri/*
    - xcodebuild clean -project memri.xcodeproj -scheme memri | xcpretty
 #   - pod install
    - xcodebuild test -project memri.xcodeproj -scheme memri -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.5' | xcpretty -s

#pages:
#  stage: build
#  script:
#  - pod install
#  - jazzy
#  artifacts:
#    paths:
#    - public
