stages:
  - build

image: ruby:2.7


build_project:
  stage: build
  script:
    - rm -rf ~/realm.memri/*
    - xcodebuild clean -workspace memri.xcworkspace -scheme memri | xcpretty
    - pod install
    - xcodebuild test -workspace memri.xcworkspace -scheme memri -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.4' | xcpretty -s

pages:
  stage: deploy
  script:
  - sudo gem install jazzy
  - jazzy
  artifacts:
    paths:
    - public
