# Ordered by output of `jazzy — help config`
output: public
clean: true
xcodebuild_arguments:
- -project
- memri.xcodeproj
- -scheme
- memri
- CODE_SIGNING_ALLOWED = NO
author: Koen van der Veen
module: memri
module_version: 0.0.1
copyright: Copyright message here
min_acl: internal
# Options : [apple | fullwidth | jony | DIRPATH]
# Which theme to use. Specify either ‘apple’ (default), one of the other built-in theme names, or the path to your mustache templates and other assets for a custom theme.Default: apple
theme: fullwidth

